'use client'

/**
 * Labeled column used by the Communication Deck shell to present
 * INCOMING and OUTGOING streams side-by-side. Owns the scroll area
 * for its list and renders an empty state when nothing matches.
 */

import { Inbox, Send } from 'lucide-react'
import type { MovementMessageRef } from '@skyhub/api'
import { useTheme } from '@/components/theme-provider'
import { MessageRawCard } from './message-raw-card'

interface Props {
  variant: 'incoming' | 'outgoing'
  messages: MovementMessageRef[]
  accentColor: string
  /** Only meaningful for outgoing */
  checkable?: boolean
  checkedIds?: Set<string>
  onToggleCheck?: (id: string) => void
  /** Slot rendered below the header (e.g. bulk action bar) */
  extraHeader?: React.ReactNode
}

export function MessageColumn({
  variant,
  messages,
  accentColor,
  checkable,
  checkedIds,
  onToggleCheck,
  extraHeader,
}: Props) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'
  const glassBg = isDark ? 'rgba(25,25,33,0.85)' : 'rgba(255,255,255,0.85)'
  const glassBorder = isDark ? 'rgba(255,255,255,0.10)' : 'rgba(0,0,0,0.10)'
  const softBorder = isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'

  const incoming = variant === 'incoming'
  const Icon = incoming ? Inbox : Send
  const label = incoming ? 'Incoming' : 'Outgoing'
  const sublabel = incoming ? 'Messages received from external systems' : 'Messages generated by SkyHub'

  return (
    <div
      className="flex-1 min-w-0 flex flex-col min-h-0 rounded-2xl overflow-hidden"
      style={{
        background: glassBg,
        border: `1px solid ${glassBorder}`,
        backdropFilter: 'blur(24px)',
      }}
    >
      {/* Column header — uses the per-module accent (Flight Ops gold), not the
          tenant accent, so it reads correctly against dark mode. */}
      <div className="flex items-center gap-3 px-4 h-12 shrink-0 border-b" style={{ borderColor: softBorder }}>
        <div className="w-[3px] h-5 rounded-full" style={{ background: 'var(--module-accent)' }} />
        <Icon size={16} style={{ color: 'var(--module-accent)' }} />
        <div className="flex flex-col">
          <span className="text-[15px] font-semibold text-hz-text leading-none">{label}</span>
          <span className="text-[13px] text-hz-text-tertiary mt-0.5">{sublabel}</span>
        </div>
        <div className="flex-1" />
        <span className="text-[13px] font-semibold" style={{ color: 'var(--module-accent)' }}>
          {messages.length}
        </span>
      </div>

      {extraHeader}

      {/* Body */}
      <div className="flex-1 min-h-0 overflow-auto custom-scrollbar">
        {messages.length === 0 ? (
          <EmptyColumn variant={variant} />
        ) : (
          <div className="flex flex-col gap-2 p-3">
            {messages.map((m) => (
              <MessageRawCard
                key={m._id}
                message={m}
                accentColor={accentColor}
                checkable={checkable}
                checked={checkedIds?.has(m._id) ?? false}
                onToggleCheck={onToggleCheck}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function EmptyColumn({ variant }: { variant: 'incoming' | 'outgoing' }) {
  const Icon = variant === 'incoming' ? Inbox : Send
  const title = variant === 'incoming' ? 'No incoming messages' : 'No outgoing messages'
  const message =
    variant === 'incoming'
      ? 'No inbound transmission sources are wired up yet. Paste a telex from the toolbar to simulate an incoming message.'
      : 'No outbound messages match the current filters.'
  return (
    <div className="h-full flex flex-col items-center justify-center text-center px-8 py-16">
      <Icon size={28} className="text-hz-text-tertiary/60 mb-3" />
      <div className="text-[15px] font-semibold text-hz-text-secondary mb-1">{title}</div>
      <div className="text-[13px] text-hz-text-tertiary max-w-[320px]">{message}</div>
    </div>
  )
}
