export { api, setApiBaseUrl, getApiBaseUrl, setAuthCallbacks } from './client'
export type { LoginResponse, RefreshResponse } from './client'
export type {
  Flight,
  AirportRef,
  AirportLookupResult,
  RunwayData,
  CityPairRef,
  BlockHourData,
  AircraftTypeRef,
  AircraftRegistrationRef,
  CountryRef,
  DelayCodeRef,
  CrewPositionRef,
  CrewPositionReferences,
  CrewComplementRef,
  CrewGroupRef,
  DutyPatternRef,
  ScheduledFlightRef,
  ScenarioRef,
  MppLeadTimeGroupRef,
  MppLeadTimeItemRef,
  FdtlFrameworkRef,
  FdtlSchemeRef,
  FdtlRuleRef,
  FdtlTableRef,
  FdtlTableCellRef,
  FdtlTabGroup,
  ExpiryCodeCategoryRef,
  ExpiryCodeRef,
  FlightServiceTypeRef,
  ReportDebriefTimes,
  CarrierCodeRef,
  CabinClassRef,
  CabinEntry,
  LopaConfigRef,
  OperatorRef,
  ReferenceStats,
  UserData,
  UserProfile,
  UserSecurity,
  UserPreferences,
  UserNotifications,
  UserDisplay,
  ActivityCodeRef,
  ActivityCodeGroupRef,
  CharterContractRef,
  CharterFlightRef,
  CharterContractStats,
  CharterPositioningLeg,
  CodeshareAgreementRef,
  CodeshareMappingRef,
  CodeshareSeatAllocationRef,
  CodeshareAgreementStats,
  CodeshareOperatingFlightRef,
  ScheduleMessageRef,
  ScheduleMessageQuery,
  ScheduleMessageStats,
  ScheduleMessageSnapshot,
  MovementMessageRef,
  MovementMessageQuery,
  MovementMessageStats,
  RevenueEntryData,
  SlotCoordinatedAirport,
  SlotSeriesRef,
  SlotDateRef,
  SlotMessageRef,
  SlotActionLogRef,
  SlotPortfolioStats,
  SlotUtilizationSummary,
  SlotCalendarWeekRef,
  SlotFleetAirportStats,
} from './client'

// ─── React Query layer ───
export { queryKeys } from './query-keys'
export * from './hooks'
